In [38]:
#1.Create a null vector of size 10 but the fifth value which is 1.


vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
#2. Create a vector with values ranging from 10 to 49
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
matrix=np.arange(9)
matrix=matrix.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)[0]

print(non_zero_indices)

[0 1 4]


In [48]:
#5.Create a 10x10 array with random values and find the minimum and maximum values.

from numpy import random

array=random.rand(10,10)

print ("array=",array)

print("minimum value=",np.mean(array))

print("minimum value=",np.max(array))

array= [[0.61155938 0.74310566 0.47849094 0.11023478 0.37562887 0.53096513
  0.01062639 0.02820728 0.94734809 0.07509532]
 [0.43577927 0.46492079 0.47726356 0.79937671 0.9627739  0.127925
  0.85966356 0.22944023 0.08261375 0.56472731]
 [0.76686865 0.72376435 0.76004364 0.98363446 0.49784235 0.39945771
  0.41083651 0.33647756 0.37743648 0.48071886]
 [0.31470987 0.39836516 0.97704058 0.73432025 0.87830441 0.14238055
  0.38408768 0.54981218 0.14959281 0.68585817]
 [0.78263718 0.36192969 0.19963911 0.97230498 0.42094604 0.02399492
  0.55831946 0.08680695 0.23371839 0.34755989]
 [0.67664778 0.51518758 0.9812591  0.37946738 0.27153814 0.22350686
  0.3730727  0.61662617 0.46091106 0.51706782]
 [0.6370302  0.93877714 0.49873999 0.49969877 0.56445595 0.00793796
  0.20863136 0.0930578  0.963414   0.10569644]
 [0.86810771 0.47492794 0.53174464 0.08717574 0.72216598 0.61417168
  0.53944149 0.37718881 0.44728851 0.38022908]
 [0.22264558 0.63816485 0.6494555  0.87426858 0.91738851 0.12365597
  0.527

In [53]:
#6.6. Create a random vector of size 30 and find the mean value.

vector=random.rand(30)
print("vector=",vector)
print("mean value=",np.mean(vector))

vector= [0.04601782 0.22160582 0.92254199 0.22430124 0.81299736 0.6895099
 0.52884861 0.99368699 0.66421719 0.30370901 0.11877446 0.17674122
 0.34345124 0.7482192  0.63783022 0.43099803 0.73059789 0.51147142
 0.71158987 0.88381853 0.43015803 0.44421082 0.22652724 0.47762733
 0.13081162 0.48390355 0.39452064 0.60586253 0.02259297 0.54523672]
mean value= 0.48207931470358395
